//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpMaterialMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErpMaterialEntities : DbContext
    {
        public ErpMaterialEntities()
            : base("name=ErpMaterialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ERP_DETAIL> ERP_DETAIL { get; set; }
        public virtual DbSet<ERP_PLAN> ERP_PLAN { get; set; }
        public virtual DbSet<ERP_PURCHASE> ERP_PURCHASE { get; set; }
        public virtual DbSet<ERP_STORAGE> ERP_STORAGE { get; set; }
        public virtual DbSet<MaterialProcurement> MaterialProcurement { get; set; }
        public virtual DbSet<MaterialStorage> MaterialStorage { get; set; }
        public virtual DbSet<MaterialUse> MaterialUse { get; set; }
        public virtual DbSet<MaterialWithDrawal> MaterialWithDrawal { get; set; }
        public virtual DbSet<PlanReport> PlanReport { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<WasteMaterials> WasteMaterials { get; set; }
    }
}
