//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpMaterialMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_STORAGE
    {
        public int ERP_STORAGE_ID { get; set; }
        public string WERKS { get; set; }
        public string LGORT { get; set; }
        public string LGNUM { get; set; }
        public string LGTYP { get; set; }
        public string LGPLA { get; set; }
        public string MATNR { get; set; }
        public string MAKTX { get; set; }
        public string MATKL { get; set; }
        public Nullable<double> VERME { get; set; }
        public Nullable<double> SALK { get; set; }
        public string MSEHL { get; set; }
        public string WDATU { get; set; }
        public string NAME_TEXTC { get; set; }
        public string AGING { get; set; }
    }
}
