//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpMaterialMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_DETAIL
    {
        public int ERP_DETAIL_ID { get; set; }
        public string MBLNR { get; set; }
        public string MJAHR { get; set; }
        public string BUDAT { get; set; }
        public string BLDAT { get; set; }
        public string BELNR { get; set; }
        public string BWART { get; set; }
        public string MATNR { get; set; }
        public string MAKTX { get; set; }
        public string MATKL { get; set; }
        public string WERKS { get; set; }
        public string LGORT { get; set; }
        public string LGORT_DESC { get; set; }
        public string SOBKZ { get; set; }
        public string LIFNR { get; set; }
        public string LIFNR_DESC { get; set; }
        public string KUNNR { get; set; }
        public Nullable<double> MENGE { get; set; }
        public string MEINS { get; set; }
        public string EBELN { get; set; }
        public string EBELP { get; set; }
        public string RSNUM { get; set; }
        public string RSPOS { get; set; }
        public string UMWRK { get; set; }
        public string UMLGO { get; set; }
        public string UMLGO_DESC { get; set; }
        public string KOSTL { get; set; }
        public string KTEXT { get; set; }
        public string PSPEL { get; set; }
        public string ZTHDW { get; set; }
    }
}
