//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpMaterialMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_PURCHASE
    {
        public int ERP_PURCHASE_ID { get; set; }
        public string EBELN { get; set; }
        public string EBELP { get; set; }
        public string MATNR { get; set; }
        public string MAKTX { get; set; }
        public Nullable<double> MENGE { get; set; }
        public string LIFNR { get; set; }
        public string LIFNR_DESC { get; set; }
        public string INTERIORCODE { get; set; }
        public string RELEASE_DATE { get; set; }
        public double NETPR { get; set; }
    }
}
