//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpMaterialMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialUse
    {
        public int MaterialUseID { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialDesc { get; set; }
        public Nullable<int> MaterialCount { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> StorageTime { get; set; }
        public Nullable<System.DateTime> TransferTime { get; set; }
        public Nullable<System.DateTime> OutStockTime { get; set; }
        public string UsePerson { get; set; }
        public string UserDept { get; set; }
        public string DeviceNo { get; set; }
        public string MaterialAge { get; set; }
    }
}
