//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpMaterialMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialProcurement
    {
        public int MaterialProcurementID { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<int> MaterialCount { get; set; }
        public string Supplier { get; set; }
        public string ContractNo { get; set; }
        public string ContractDate { get; set; }
        public string ProcurementPrice { get; set; }
        public Nullable<System.DateTime> MaterialArrivalDate { get; set; }
    }
}
