//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpMaterialMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialWithDrawal
    {
        public int MaterialWithDrawalID { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialDesc { get; set; }
        public string MaterialCount { get; set; }
        public string StorageTime { get; set; }
        public string TransferTime { get; set; }
        public string OutStockTime { get; set; }
        public string UsePerson { get; set; }
        public string UserDept { get; set; }
        public string Custodian { get; set; }
        public string ReturnDate { get; set; }
        public string ProjectName { get; set; }
    }
}
