//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpMaterialMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockID { get; set; }
        public string MaterialGroup { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialDesc { get; set; }
        public string MaterialCount { get; set; }
        public Nullable<double> Amount { get; set; }
        public string UnitOfMeasurement { get; set; }
        public string StockNum { get; set; }
        public Nullable<System.DateTime> StorageTime { get; set; }
        public string WarehousePosition { get; set; }
        public string BookKeeper { get; set; }
    }
}
